# Generated by Django 2.2 on 2020-09-23 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_readiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_readiness.Assessment')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_readiness.Objective')),
            ],
        ),
    ]
