# Generated by Django 2.2 on 2020-10-08 18:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_readiness', '0004_auto_20200927_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('section_1', models.BooleanField(verbose_name='Section 1 Graph')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDesignQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('treatment_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_readiness.TreatmentDesign')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='part_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='select_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(blank=True, to='thesis_readiness.Question'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='students',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ObjectiveOrdering',
        ),
        migrations.AddField(
            model_name='graph',
            name='questions',
            field=models.ManyToManyField(blank=True, to='thesis_readiness.Question'),
        ),
        migrations.AddField(
            model_name='graph',
            name='treatment_design',
            field=models.ManyToManyField(to='thesis_readiness.TreatmentDesign'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='section_1_treatment_designs',
            field=models.ManyToManyField(blank=True, related_name='assessment_qty_1', to='thesis_readiness.TreatmentDesignQuantity'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='section_2_treatment_designs',
            field=models.ManyToManyField(blank=True, related_name='assessment_qty_2', to='thesis_readiness.TreatmentDesignQuantity'),
        ),
        migrations.AddField(
            model_name='assessmentresponse',
            name='graph',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='thesis_readiness.Graph'),
        ),
    ]
