# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
#version: '2'

networks:
  webnet:
    driver: overlay
    attachable: true # Needed in order to run custom commands in the container

services:
    nginx:
        restart: always
        image: nginx:1.23-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    waypoints-server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/waypoints-backend/Dockerfile
        entrypoint: /app/docker/waypoints-backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/waypoints-backend/django_static
        expose:
            - 8000
        environment:
            DEBUG: "True"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: waypoints-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    nluaba-server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nluaba-backend/Dockerfile
        entrypoint: /app/docker/nluaba-backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/nluaba-backend/django_static
        expose:
            - 8000
        environment:
            DEBUG: "True"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: nluaba-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    jake-server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/jake-backend/Dockerfile
        entrypoint: /app/docker/jake-backend/server-entrypoint.sh
        volumes:
            - static_volume:/app/jake-backend/django_static
        expose:
            - 8000
        environment:
            DEBUG: "TRUE"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: jake-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    waypoints-worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/waypoints-backend/Dockerfile
        entrypoint: /app/docker/waypoints-backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/waypoints-backend/django_static
        environment:
            DEBUG: "True"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: waypoints-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        depends_on:
            - waypoints-server
            - redis
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    nluaba-worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nluaba-backend/Dockerfile
        entrypoint: /app/docker/nluaba-backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/nluaba-backend/django_static
        environment:
            DEBUG: "True"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: nluaba-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        depends_on:
            - nluaba-server
            - redis
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    jake-worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/jake-backend/Dockerfile
        entrypoint: /app/docker/jake-backend/worker-entrypoint.sh
        volumes:
            - static_volume:/app/jake-backend/django_static
        environment:
            DEBUG: "True"
            REDIS_URL: 'redis://redis:6379'
            DJANGO_DB: postgresql
            POSTGRES_HOST: kleinapp-database-do-user-17842599-0.k.db.ondigitalocean.com
            POSTGRES_NAME: jake-db
            POSTGRES_USER: doadmin
            POSTGRES_PORT: 25060
            S3_ACCESS: /run/secrets/S3_ACCESS
            S3_SECRET: /run/secrets/S3_SECRET
            C_URL: /run/secrets/CLOUDINARY_URL
            POSTGRES_PASSWORD: /run/secrets/POSTGRES_PASSWORD
        depends_on:
            - jake-server
            - redis
        secrets:
            - S3_ACCESS
            - S3_SECRET
            - CLOUDINARY_URL
            - POSTGRES_PASSWORD
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379

secrets:
    S3_ACCESS:
        environment: S3_ACCESS
    S3_SECRET:
        environment: S3_SECRET
    CLOUDINARY_URL:
        environment: CLOUDINARY_URL
    POSTGRES_PASSWORD:
        environment: POSTGRES_PASSWORD

volumes:
    static_volume: {}