# Generated by Django 2.2 on 2022-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='video_names',
            field=models.TextField(blank=True),
        ),
    ]
