# Generated by Django 2.2 on 2022-08-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0002_auto_20220728_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestionresponse',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
