# Generated by Django 2.2 on 2022-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0003_assessmentquestionresponse_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseanswer',
            name='response_label',
            field=models.TextField(),
        ),
    ]
