# Generated by Django 2.2 on 2022-08-17 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ica', '0004_auto_20220804_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='in_situ_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MC', 'Multiple Choice'), ('SA', 'Short Answer'), ('CSA', 'Column Short Answer'), ('DD', 'Drag and Drop'), ('IS', 'In Situ')], max_length=5),
        ),
        migrations.CreateModel(
            name='InSituAssessmentInstance',
            fields=[
                ('assessmentinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ica.AssessmentInstance')),
                ('technician', models.TextField()),
                ('users', models.ManyToManyField(blank=True, related_name='in_situ_assessment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ica.assessmentinstance',),
        ),
        migrations.CreateModel(
            name='InSituAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ica.Question')),
            ],
        ),
    ]
