# Generated by Django 2.2 on 2022-08-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0005_auto_20220817_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
