# Generated by Django 2.2 on 2022-08-19 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0006_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ica.Task'),
        ),
    ]
