# Generated by Django 2.2 on 2022-08-19 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0007_auto_20220819_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentinstance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icainstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
