# Generated by Django 2.2 on 2022-08-22 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ica', '0008_auto_20220819_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='InSituAssessmentQuestionResponse',
            fields=[
                ('assessmentquestionresponse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ica.AssessmentQuestionResponse')),
                ('required', models.BooleanField(default=False)),
                ('respondent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insituaqr', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('ica.assessmentquestionresponse',),
        ),
    ]
