# Generated by Django 2.2 on 2022-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ica', '0009_insituassessmentquestionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestionresponse',
            name='begun',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
