# Generated by Django 2.2 on 2022-12-19 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ica', '0010_assessmentquestionresponse_begun'),
    ]

    operations = [
        migrations.AddField(
            model_name='insituassessmentinstance',
            name='confirmed_supervisors',
            field=models.ManyToManyField(blank=True, related_name='in_situ_assessment_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
