# Generated by Django 2.2 on 2019-05-20 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realinstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
