# Generated by Django 2.2.7 on 2020-04-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0007_testresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='feedback_released',
            field=models.BooleanField(default=False),
        ),
    ]
