# Generated by Django 2.2.7 on 2020-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0008_testinstance_feedback_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='testresponse',
            name='earned_points',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
