# Generated by Django 2.2.7 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0009_auto_20200429_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answer_3',
            field=models.TextField(blank=True),
        ),
    ]
