# Generated by Django 2.2.7 on 2020-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0010_auto_20200527_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='auto_release_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
