# Generated by Django 2.2 on 2021-03-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0013_auto_20210217_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='multiple_sittings',
            field=models.BooleanField(default=False, verbose_name='Can be done over multiple sittings'),
        ),
    ]
