# Generated by Django 2.2 on 2021-06-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0014_test_multiple_sittings'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='retake',
            field=models.BooleanField(default=True, verbose_name='Can be retaken once completed'),
        ),
    ]
