# Generated by Django 2.1.3 on 2019-01-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safmeds', '0002_auto_20190103_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresponse',
            name='manual_correct',
            field=models.BooleanField(default=False),
        ),
    ]
