# Generated by Django 2.1.3 on 2019-01-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safmeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(editable=False, to='safmeds.Card'),
        ),
    ]
