# Generated by Django 2.2.7 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safmeds', '0004_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='test_out',
            field=models.BooleanField(default=False),
        ),
    ]
