# Generated by Django 2.2.7 on 2020-07-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safmeds', '0005_deck_test_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresponse',
            name='latency',
            field=models.DurationField(default=None, null=True),
        ),
    ]
