# Generated by Django 2.2 on 2021-03-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safmeds', '0006_practiceresponse_latency'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='correct',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='practice',
            name='incorrect',
            field=models.SmallIntegerField(default=0),
        ),
    ]
