# Generated by Django 5.1.5 on 2025-01-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_questions',
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('header', models.TextField()),
                ('assessment_questions', models.ManyToManyField(to='jakeapp.assessmentquestion')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_sections',
            field=models.ManyToManyField(to='jakeapp.assessmentsection'),
        ),
    ]
