# Generated by Django 5.1.6 on 2025-03-02 22:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakeapp', '0004_assessmentquestionresponse_assessment_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('module_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jakeapp.moduleinstance')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jakeapp.modulesection')),
            ],
        ),
    ]
