# Generated by Django 2.2.7 on 2020-03-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20200320_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
