# Generated by Django 2.2.7 on 2020-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_question_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresponse',
            name='feedback',
            field=models.TextField(default=''),
        ),
    ]
