# Generated by Django 2.2.7 on 2020-05-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_testresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
