# Generated by Django 2.2 on 2020-11-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_testinstance_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='multiple_sittings',
            field=models.BooleanField(default=False, verbose_name='Can be done over multiple sittings'),
        ),
    ]
