# Generated by Django 2.2 on 2020-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_test_multiple_sittings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresponse',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
