# Generated by Django 2.2 on 2022-03-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_auto_20201106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='content_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.ContentArea'),
        ),
    ]
