# Generated by Django 2.2 on 2020-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_readiness', '0002_objectiveordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
