# Generated by Django 2.2 on 2020-09-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis_readiness', '0003_auto_20200924_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(blank=True, related_name='correct_answer', to='thesis_readiness.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='incorrect_answers',
            field=models.ManyToManyField(blank=True, related_name='incorrect_answer', to='thesis_readiness.Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='objectives',
            field=models.ManyToManyField(blank=True, to='thesis_readiness.Objective'),
        ),
    ]
