# Generated by Django 2.2 on 2019-04-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Limit. Note if you just put a number, it defaults to seconds. Can accept XX:XX'),
        ),
    ]
