# Generated by Django 2.2 on 2021-05-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_course_maintenance_maintenanceinstance_maintenanceresponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['name']},
        ),
    ]
