# Generated by Django 2.2 on 2024-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_auto_20210504_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceinstance',
            name='finished',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
