# Generated by Django 2.2 on 2024-09-05 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_auto_20240828_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
