# Generated by Django 2.2 on 2020-11-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0011_test_auto_release_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestionOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.SmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realexams.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realexams.Test')),
            ],
        ),
    ]
