# Generated by Django 5.1.1 on 2024-09-25 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realexams', '0014_test_multiple_sittings'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
